name: Run Tests

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        . $HOME/.cargo/env
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: Compile dependencies
      run: |
        uv pip compile requirements.in -o requirements.txt

    - name: Install dependencies
      run: |
        uv pip install --python=$(which python3) -r requirements.txt

    - name: Run tests
      run: |
        pytest
