name: Run Tests

on:
  workflow_call:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Set up Node
      uses: actions/setup-node@v4
      with:
          node-version: 20

    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        . $HOME/.cargo/env
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: Compile dependencies
      run: |
        uv pip compile requirements.in dev-requirements.in -o requirements.txt

    - name: Install dependencies
      run: |
        uv pip install --python=$(which python3) -r requirements.txt
        npm ci
        npm run build
        python -m playwright install --with-deps firefox

    - name: Run tests
      env:
        SECRET_KEY: im_so_secret
      run: |
        npm run dev &
        pytest
        pkill node

    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: test-results/
        retention-days: 30

    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: har
        path: test_zip_file_upload_invalid_zip_client_side_validation.har
        retention-days: 30
